env: eslint-plugin-import  추가
10-rolling/rollingPolling pull request #23
Opened 2023-11-04 13:59 UTC by ngsy

## ✅ 작업 내용

- [ ] eslint-plugin-import 패키지 추가(import 자동정렬)

## 📍 리뷰 포인트

- x
- 

## 🗣️ 기타 사항

- import가 자동정렬 되지않아서 갓 슬희님이 알려주셨습니다.

- vscode setting.json 추가설정 필요합니다.

setting.json
`editor.codeActionsOnSave": {
    "source.fixAll.stylelint": true,   

    **"source.fixAll.eslint": true**
  },`

2023-11-04 14:15 UTC, hanseulhee approved these changes
👍🏻👍🏻 고생하셨습니다

빌드가 안되는데 globalstyle 파일 esllint 적용하고 올려주시면 좋을 것 같아요 😃
(설치하면서 충돌났는데 해결해주시면 될 것 같아요!)

2023-11-04 14:18 UTC, ngsy commented
> 👍🏻👍🏻 고생하셨습니다
> 
> 빌드가 안되는데 globalstyle 파일 esllint 적용하고 올려주시면 좋을 것 같아요 😃 (설치하면서 충돌났는데 해결해주시면 될 것 같아요!)

넵! 바로  수정해볼게요

2023-11-05 04:22 UTC, oauch requested changes
수고하셨습니다 👍
(지금 package-lock.json 파일 충돌나는거 같은데 확인 부탁드립니다!)

2023-11-05 05:28 UTC, miniposi commented
저도 pr에서 같은 충돌이 나네요! ㅠㅠ

2023-11-05 06:53 UTC, ngsy commented
> 수고하셨습니다 👍 (지금 package-lock.json 파일 충돌나는거 같은데 확인 부탁드립니다!)

npm 버전이 달라서 pakage-lock.json 파일이 다르게 설정 되었었습니다. 

npm 버전 10.1.0 -> 9.8.1 으로 다운그레이드 하여 다시 설정하였습니다

2023-11-05 09:08 UTC, merged